# Generated by Django 5.1.7 on 2025-07-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('online', '線上'), ('offline', '實體')], help_text='諮詢方式：線上或實體', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='預約當時的收費金額', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', help_text='預約狀態', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('slot', models.OneToOneField(help_text='對應的可預約時段；被預約後自動標記為已預約', on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='therapists.availableslot')),
                ('therapist', models.ForeignKey(help_text='預約的心理師', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='therapists.therapistprofile')),
            ],
        ),
    ]
