# Generated by Django 4.2 on 2025-07-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_add_appointmentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='確認時間', null=True),
        ),
    ]
