# Generated by Django 4.2 on 2025-07-24 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0004_migrate_specialties_data'),
        ('appointments', '0006_appointment_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(blank=True, help_text='預約的心理師（可由管理員後續分配）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='therapists.therapistprofile'),
        ),
    ]
