# Generated by Django 5.2.4 on 2025-08-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_therapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('reminder_24h', '24小時提醒'), ('reminder_2h', '2小時提醒'), ('follow_up', '追蹤郵件'), ('feedback_request', '回饋請求')], help_text='郵件類型', max_length=20)),
                ('recipient_email', models.EmailField(help_text='收件人郵箱', max_length=254)),
                ('scheduled_time', models.DateTimeField(help_text='預定發送時間')),
                ('status', models.CharField(choices=[('pending', '待發送'), ('sent', '已發送'), ('failed', '發送失敗'), ('cancelled', '已取消')], default='pending', help_text='郵件狀態', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='實際發送時間', null=True)),
                ('error_message', models.TextField(blank=True, help_text='錯誤訊息（如果發送失敗）')),
                ('retry_count', models.IntegerField(default=0, help_text='重試次數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(help_text='對應的預約', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='appointments.appointment')),
            ],
            options={
                'ordering': ['scheduled_time'],
                'unique_together': {('appointment', 'email_type')},
            },
        ),
    ]
