# Generated by Django 5.2.4 on 2025-08-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_consultation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attendance_status',
            field=models.CharField(choices=[('pending', '待確認出席'), ('attended', '已到'), ('no_show', '未到'), ('late', '遲到'), ('completed', '已完成諮商')], default='pending', help_text='個案出席狀態', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attendance_time',
            field=models.DateTimeField(blank=True, help_text='出席確認時間', null=True),
        ),
    ]
