# Generated by Django 5.2.4 on 2025-08-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_add_attendance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='attendance_status',
            field=models.CharField(choices=[('pending', '待確認出席'), ('attended', '已到'), ('no_show', '未到'), ('leave', '請假')], default='pending', help_text='個案出席狀態', max_length=20),
        ),
    ]
