# Generated by Django 5.2.4 on 2025-08-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_create_articleimage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, help_text='文章摘要，用於列表頁顯示，最多300字', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='特色圖片，顯示在文章列表和詳細頁面頂部', null=True, upload_to='articles/featured/'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, help_text='是否發布，未發布的文章不會在前端顯示'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="標籤列表，JSON 陣列格式，例如 ['焦慮','人際關係']（選填）"),
        ),
    ]
