# Generated by Django 5.1.7 on 2025-07-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_preferredperiod_appointment_confirmed_at_and_more'),
    ]

    operations = [
    ]
