# Generated by Django 5.1.7 on 2025-07-23 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20250723_1543'),
        ('therapists', '0004_migrate_specialties_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferredperiod',
            options={'ordering': ['date', 'period']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preferred',
        ),
        migrations.AddField(
            model_name='preferredperiod',
            name='appointment',
            field=models.ForeignKey(help_text='對應的預約', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_periods', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='preferredperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('online', '線上'), ('offline', '實體')], help_text='諮詢方式：線上或實體', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='建立時間'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='預約當時的收費金額', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(blank=True, help_text='對應的可預約時段；被預約後自動標記為已預約', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='therapists.availableslot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', help_text='預約狀態', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(help_text='預約的心理師', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='therapists.therapistprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(help_text='預約的使用者', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preferredperiod',
            name='date',
            field=models.DateField(help_text='偏好日期'),
        ),
        migrations.AlterField(
            model_name='preferredperiod',
            name='period',
            field=models.CharField(choices=[('morning', '上午'), ('afternoon', '下午'), ('evening', '晚上')], help_text='偏好時段', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='preferredperiod',
            unique_together={('appointment', 'date', 'period')},
        ),
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='用戶姓名', max_length=100)),
                ('phone', models.CharField(blank=True, default='', help_text='聯絡電話', max_length=20)),
                ('main_concerns', models.TextField(blank=True, default='', help_text='主要關注議題')),
                ('previous_therapy', models.BooleanField(default=False, help_text='是否曾接受過心理諮商')),
                ('urgency', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', help_text='緊急程度', max_length=20)),
                ('special_needs', models.TextField(blank=True, default='', help_text='特殊需求')),
                ('specialty_requested', models.IntegerField(blank=True, help_text='請求的專業領域ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(help_text='對應的預約', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='appointments.appointment')),
            ],
        ),
    ]
