# Generated by Django 5.2.4 on 2025-08-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_scheduledemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemail',
            name='email_type',
            field=models.CharField(choices=[('reminder_24h_user', '24小時提醒(用戶)'), ('reminder_24h_therapist', '24小時提醒(心理師)')], help_text='郵件類型', max_length=30),
        ),
    ]
