# Generated by Django 5.2.4 on 2025-08-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_scheduledemail_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='管理員備註（僅管理員可見）'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_room',
            field=models.CharField(blank=True, choices=[('room_1', '諮商室 A'), ('room_2', '諮商室 B'), ('room_3', '諮商室 C'), ('room_4', '諮商室 D'), ('room_5', '會談室 1'), ('room_6', '會談室 2'), ('online_room', '線上會議室')], help_text='指定的諮商室', max_length=20, null=True),
        ),
    ]
