# Generated by Django 5.2.4 on 2025-08-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_room',
            field=models.CharField(blank=True, choices=[('room_2', '諮商室 2'), ('room_3', '諮商室 3'), ('room_4', '諮商室 4'), ('room_5', '諮商室 5'), ('online_room', '線上會議室')], help_text='指定的諮商室', max_length=20, null=True),
        ),
    ]
