# Generated by Django 4.2 on 2025-07-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_update_risk_level_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
