# Generated by Django 5.1.7 on 2025-07-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='文章標題，長度上限200字', max_length=200)),
                ('content', models.TextField(help_text='文章內文，可包含多行文字')),
                ('tags', models.JSONField(default=list, help_text="標籤列表，JSON 陣列格式，例如 ['焦慮','人際關係']")),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text='發佈時間，建立時自動填入')),
            ],
        ),
    ]
