# Generated by Django 5.1.7 on 2025-07-28 06:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='文章內文，支援富文本編輯和圖片上傳'),
        ),
    ]
