# Generated by Django 5.2.4 on 2025-08-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='圖片檔案', upload_to='articles/images/')),
                ('caption', models.CharField(blank=True, help_text='圖片說明文字', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='排序順序，數字越小越靠前')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='上傳時間')),
                ('article', models.ForeignKey(help_text='所屬文章', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article')),
            ],
            options={
                'verbose_name': '文章圖片',
                'verbose_name_plural': '文章圖片',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
