# Generated by Django 5.2.4 on 2025-08-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0004_migrate_specialties_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name': '專業領域', 'verbose_name_plural': '專業領域'},
        ),
        migrations.DeleteModel(
            name='SpecialtyCategory',
        ),
    ]
