# Generated by Django 5.2.4 on 2025-08-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0005_remove_specialty_category_alter_specialty_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='consultation_modes',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='publications',
        ),
    ]
