# Generated by Django 5.2.4 on 2025-08-08 03:26

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, verbose_name='分類說明')),
                ('color', models.CharField(default='#007bff', help_text='分類標籤顏色，例如: #007bff', max_length=7, verbose_name='標籤顏色')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('order', models.IntegerField(default=0, help_text='排序權重，數字越小排序越前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '公告分類',
                'verbose_name_plural': '公告分類',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('summary', models.CharField(blank=True, help_text='簡短摘要，將顯示在列表頁面', max_length=300, verbose_name='摘要')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='支援富文本編輯，可插入圖片和連結', verbose_name='內容')),
                ('featured_image', models.ImageField(blank=True, help_text='特色圖片，建議尺寸: 800x400px', null=True, upload_to='announcements/featured/%Y/%m/%d/', verbose_name='特色圖片')),
                ('priority', models.CharField(choices=[('low', '一般'), ('medium', '重要'), ('high', '緊急')], default='low', max_length=10, verbose_name='重要程度')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已發布'), ('archived', '已封存')], default='draft', max_length=10, verbose_name='狀態')),
                ('is_pinned', models.BooleanField(default=False, help_text='置頂的公告會優先顯示', verbose_name='置頂')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='是否在首頁顯示', verbose_name='首頁顯示')),
                ('publish_date', models.DateTimeField(blank=True, help_text='排程發布時間，留空則立即發布', null=True, verbose_name='發布時間')),
                ('expire_date', models.DateTimeField(blank=True, help_text='過期時間，過期後自動隱藏', null=True, verbose_name='過期時間')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='按讚數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='announcements.announcementcategory', verbose_name='分類')),
            ],
            options={
                'verbose_name': '最新消息',
                'verbose_name_plural': '最新消息',
                'ordering': ['-is_pinned', '-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/images/%Y/%m/%d/', verbose_name='圖片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='圖片說明')),
                ('order', models.IntegerField(default=0, help_text='顯示順序', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='announcements.announcement', verbose_name='所屬公告')),
            ],
            options={
                'verbose_name': '公告圖片',
                'verbose_name_plural': '公告圖片',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
