# Generated by Django 5.2.4 on 2025-08-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='priority',
        ),
    ]
