# Generated by Django 5.2.4 on 2025-08-11 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='日期', unique=True)),
                ('unique_visitors', models.PositiveIntegerField(default=0, help_text='獨立訪客數')),
                ('total_pageviews', models.PositiveIntegerField(default=0, help_text='總頁面瀏覽數')),
                ('total_sessions', models.PositiveIntegerField(default=0, help_text='總會話數')),
                ('avg_session_duration', models.DurationField(blank=True, help_text='平均會話時長', null=True)),
                ('avg_pages_per_session', models.DecimalField(blank=True, decimal_places=2, help_text='每會話平均頁面數', max_digits=5, null=True)),
                ('bounce_rate', models.DecimalField(blank=True, decimal_places=2, help_text='跳出率', max_digits=5, null=True)),
                ('new_visitors', models.PositiveIntegerField(default=0, help_text='新訪客數')),
                ('returning_visitors', models.PositiveIntegerField(default=0, help_text='回訪用戶數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '每日統計',
                'verbose_name_plural': '每日統計',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PopularPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(help_text='頁面路徑', max_length=500)),
                ('page_title', models.CharField(blank=True, help_text='頁面標題', max_length=255)),
                ('page_category', models.CharField(blank=True, help_text='頁面分類', max_length=100)),
                ('total_views', models.PositiveIntegerField(default=0, help_text='總瀏覽次數')),
                ('unique_views', models.PositiveIntegerField(default=0, help_text='獨立瀏覽次數')),
                ('avg_time_on_page', models.PositiveIntegerField(blank=True, help_text='平均停留時間(秒)', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='最後更新時間')),
            ],
            options={
                'verbose_name': '熱門頁面',
                'verbose_name_plural': '熱門頁面',
                'ordering': ['-total_views'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='會話ID', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='訪客IP地址')),
                ('user_agent', models.TextField(blank=True, help_text='瀏覽器用戶代理')),
                ('country', models.CharField(blank=True, help_text='國家', max_length=100)),
                ('city', models.CharField(blank=True, help_text='城市', max_length=100)),
                ('device_type', models.CharField(blank=True, help_text='設備類型(mobile/desktop/tablet)', max_length=50)),
                ('browser', models.CharField(blank=True, help_text='瀏覽器', max_length=100)),
                ('os', models.CharField(blank=True, help_text='操作系統', max_length=100)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now, help_text='首次訪問時間')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, help_text='最後活動時間')),
                ('page_views', models.PositiveIntegerField(default=0, help_text='頁面瀏覽數')),
                ('session_duration', models.DurationField(blank=True, help_text='會話持續時間', null=True)),
                ('referrer', models.URLField(blank=True, help_text='來源網址')),
                ('utm_source', models.CharField(blank=True, help_text='UTM來源', max_length=255)),
                ('utm_medium', models.CharField(blank=True, help_text='UTM媒介', max_length=255)),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM活動', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='關聯用戶(如已登入)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '訪客會話',
                'verbose_name_plural': '訪客會話',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(help_text='頁面路徑', max_length=500)),
                ('page_title', models.CharField(blank=True, help_text='頁面標題', max_length=255)),
                ('page_category', models.CharField(blank=True, help_text='頁面分類', max_length=100)),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, help_text='訪問時間')),
                ('time_on_page', models.PositiveIntegerField(blank=True, help_text='頁面停留時間(秒)', null=True)),
                ('scroll_depth', models.PositiveIntegerField(blank=True, help_text='滾動深度百分比', null=True)),
                ('is_bounce', models.BooleanField(default=True, help_text='是否跳出')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='關聯會話', on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.visitorsession')),
            ],
            options={
                'verbose_name': '頁面瀏覽',
                'verbose_name_plural': '頁面瀏覽',
                'ordering': ['-visit_time'],
            },
        ),
    ]
