# Generated by Django 5.1.7 on 2025-07-11 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responseitem',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.choice'),
        ),
        migrations.AddField(
            model_name='responseitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
        migrations.AddField(
            model_name='responseitem',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.response'),
        ),
        migrations.AddField(
            model_name='response',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.test'),
        ),
    ]
