# Generated by Django 5.1.7 on 2025-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='risk_level',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
