# Generated by Django 5.1.7 on 2025-07-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='心理師姓名', max_length=100)),
                ('title', models.CharField(help_text='心理師頭銜，例如：諮商所督導', max_length=100)),
                ('license_number', models.CharField(help_text='證照編號（如：諮心字第000485號）', max_length=50)),
                ('education', models.TextField(help_text='學歷與證書')),
                ('experience', models.TextField(help_text='經歷描述')),
                ('specialties', models.TextField(help_text='專長描述（理論取向／服務對象）')),
                ('beliefs', models.TextField(help_text='個人信念／諮商理念')),
                ('publications', models.JSONField(default=list, help_text='文章列表（字串陣列）')),
                ('photo', models.ImageField(blank=True, help_text='心理師頭像照片', null=True, upload_to='therapists/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('consultation_modes', models.JSONField(default=list, help_text="可提供諮詢模式列表，範例：['online','offline']")),
                ('pricing', models.JSONField(default=dict, help_text="各模式收費，範例：{'online':2000,'offline':3000}")),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', '週一'), ('tuesday', '週二'), ('wednesday', '週三'), ('thursday', '週四'), ('friday', '週五'), ('saturday', '週六'), ('sunday', '週日')], help_text='星期幾', max_length=9)),
                ('start_time', models.TimeField(help_text='開始時間')),
                ('end_time', models.TimeField(help_text='結束時間')),
                ('therapist', models.ForeignKey(help_text='所屬心理師', on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='therapists.therapistprofile')),
            ],
            options={
                'ordering': ['therapist', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False, help_text='此時段是否已被預約')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapists.therapistprofile')),
            ],
        ),
    ]
