# Generated by Django 5.1.7 on 2025-07-16 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableslot',
            options={'ordering': ['therapist', 'slot_time']},
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='對應的 Django 使用者帳號', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapistprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availableslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='day_of_week',
            field=models.CharField(choices=[('monday', '週一'), ('tuesday', '週二'), ('wednesday', '週三'), ('thursday', '週四'), ('friday', '週五'), ('saturday', '週六'), ('sunday', '週日')], max_length=9),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='therapists.therapistprofile'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='beliefs',
            field=models.TextField(help_text='諮商信念 / 理念'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='consultation_modes',
            field=models.JSONField(default=list, help_text="可提供諮詢模式，例如：['online','offline']"),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='education',
            field=models.TextField(help_text='學歷 / 證書'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='license_number',
            field=models.CharField(help_text='證照字號', max_length=50),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='name',
            field=models.CharField(help_text='姓名', max_length=100),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='therapists/'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='pricing',
            field=models.JSONField(default=dict, help_text="各模式收費，如：{'online':1200,'offline':1500}"),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='specialties',
            field=models.TextField(help_text='專長 (理論取向 / 服務族群)'),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='title',
            field=models.CharField(help_text='頭銜，如：諮商所督導', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='availableslot',
            unique_together={('therapist', 'slot_time')},
        ),
        migrations.AlterUniqueTogether(
            name='availabletime',
            unique_together={('therapist', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
