# Generated by Django 5.1.7 on 2025-07-22 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_alter_availableslot_options_therapistprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分類名稱', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='分類說明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '專業領域分類',
                'verbose_name_plural': '專業領域分類',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='specialties_text',
            field=models.TextField(blank=True, help_text='專長文字描述（舊格式，逐步淘汰）'),
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='specialties',
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='專業領域名稱', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='專業領域說明')),
                ('is_active', models.BooleanField(default=True, help_text='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='所屬分類', on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='therapists.specialtycategory')),
            ],
            options={
                'verbose_name': '專業領域',
                'verbose_name_plural': '專業領域',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, help_text='專業領域（關聯式）', related_name='therapists', to='therapists.specialty'),
        ),
    ]
